# 変数定義ゾーン
[variables]
name = "yuma_noguchi"
id = 0x1

[zip]
# zipファイルを作る元となるディレクトリの名前
# 作成されたzipファイルの元ファイルとなるディレクトリは残す
file_name = "abc.zip"
# パスワード (オプション)
password = "test123"

# file定義ゾーン
[file1]
# variablesで定義した定数をjinja2みたいに埋め込むことができ、これはzipのfile_nameへとコピーするコピー元とコピー先を表す。場合によってはtoによってリネームする。toはzipファイルの元ディレクトリをルートとする。
from = "{{name}}\\foobar.txt"
to = "renamed_foobar.txt"

[file2]
from = "{{name}}\\foobar2.txt"
to = "{{id}}\\renamed_foobar2.txt"

[file3]
from = "{{name}}\\{{id}}\\foobar2.txt"
to = "{{id}}\\renamed_foobar2.txt"



